### ISSUE TITLE
list down available issues in a interface

### ISSUE THREAD

**Issue by charithsoori** [99xt/99xt.github.io#3]

**Comment by dinukadesilva** [comment]
I would say that it makes sense to list all the activities happening in the organization rather just listing the issues

**Comment by dinukadesilva** [comment]
I have been already working on this. Await for a pull request from me

**Comment by dinukadesilva** [comment]
@charithsoori @chamathpali @rehrumesh 
Here is a screenshot of this. (Still in progress)
![image](https://user-images.githubusercontent.com/10680296/29739748-da10a364-8a62-11e7-8516-40cc20cb521b.png)
