### ISSUE TITLE
Show stars count, number of forks and the repo language 

### ISSUE THREAD

**Issue by chamathpali** [99xt/99xt.github.io#30]

**Comment by chamathpali** [comment]
@raashidA can you come up with a layout sketch

**Comment by charithsoori** [comment]
icons 
Forks and start - Can use gihub one
![image](https://cloud.githubusercontent.com/assets/498456/19847368/61928bc8-9f6c-11e6-8c30-71dcd59a6eb5.png)

**Comment by chamathpali** [comment]
Added Repo language in a label

**Comment by charithsoori** [comment]
@chamathpali  Showing technologies used inside will probably give an edge . What do you think ? Was a task for it ?

**Comment by chamathpali** [comment]
didnt get you? you mean like a breakdown?

**Comment by raashidA** [comment]
![cards](https://cloud.githubusercontent.com/assets/2629666/19853484/7aa4629e-9f8f-11e6-90a5-908860497c29.jpg)

**Comment by charithsoori** [comment]
@chamathpali  like in above serverles-hot-lambda . I think we can have programming language before star
Technologies mean - serveless , angular

**Comment by chamathpali** [comment]
@charithsoori Currently with the API we can only get the main language of the repo..

**Comment by chamathpali** [comment]
#32  needs styling

**Comment by charithsoori** [comment]
Refer https://github.com/fossasia/open-event-webapp/issues/660 [https://github.com/fossasia/open-event-webapp#components-and-technology]

We could do the same and force each repository to add a custom configuration file name(github.io.config). 

File will have following fields
technology : description                              
SASS          : SASS to write optimized CSS. 

We should find a common repository to get shields/badge forgiven technology .


What do you think ?

**Comment by chamathpali** [comment]
yeah it would be  nice

**Comment by chamathpali** [comment]
#32
