### ISSUE TITLE
Navigate to repository Github page option in the popup

### ISSUE THREAD

**Issue by dilumn** [99xt/99xt.github.io#40]
Right now when we select a repository there is a popup with a button to go to the repository. We can add another button to navigate to the repository Github page which every repository can maintain their own website on `gh-pages` branch.

Right now `scikit-api` Github page is on http://opensource.99xtechnology.com/scikit-api/

But for that every repository should maintain a well written website.

Just an idea I got. Open for suggestions

**Comment by charithsoori** [comment]
That's a good idea . I think we can use [api:https://developer.github.com/v3/repos/pages/] to enable disable this button based on page availability . 

Anyone to take this idea forward ?

**Comment by chamathpali** [comment]
Every repo maintaining a website is the issue...

**Comment by chamathpali** [comment]
any updates?

**Comment by chamathpali** [comment]
Will close this issue for now since there's a lack of pages in most of the repos
