### ISSUE TITLE
Add random colours to project cards.

### ISSUE THREAD

**Issue by raashidA** [99xt/99xt.github.io#7]
Refer below code and Image
https://github.com/davidmerfield/randomColor

**Border  Size 4px**

![cards](https://cloud.githubusercontent.com/assets/2629666/19771411/7fb9d3a2-9c80-11e6-84e8-2196da8bfe50.jpg)

**Comment by satiewaltz** [comment]
I'll take this on, will send a PR in a while.

**Comment by charithsoori** [comment]
Perfect. 👍

**Comment by chamathpali** [comment]
@satiewaltz https://randomcolor.llllll.li/ have a look at this too. for generating random colors

**Comment by satiewaltz** [comment]
Using jQuery destroys the original CSS hover effect on the project cards. I added a mouse event in place of this, switching to a gray border on hover. 

_(Top right is currently hovered)_

![image](https://cloud.githubusercontent.com/assets/16066222/19804684/d8f3e130-9cdd-11e6-8d31-7bda230c3835.png)

@charithsoori I will checkout that library before submitting the PR, if it can give back better looking colors.

**Comment by charithsoori** [comment]
This looks nice . I am not clear about one thing . What is the underline library ?

**Comment by satiewaltz** [comment]
:confused: I don't know. It was there when I downloaded the repo.

**Comment by charithsoori** [comment]
Thats fine can we check it ?

**Comment by satiewaltz** [comment]
@charithsoori http://underscorejs.org/

**Comment by satiewaltz** [comment]
Close the pull request if you found my code useful, saves other people time.

**Comment by chamathpali** [comment]
Nice job 👍
